/*
 *************************************************************************
 *                                                                       *
 *  LightningJ                                                           *
 *                                                                       *
 *  This software is free software; you can redistribute it and/or       *
 *  modify it under the terms of the GNU Lesser General Public License   *
 *  (LGPL-3.0-or-later)                                                  *
 *  License as published by the Free Software Foundation; either         *
 *  version 3 of the License, or any later version.                      *
 *                                                                       *
 *  See terms of license at gnu.org.                                     *
 *                                                                       *
 *************************************************************************/
package org.lightningj.paywall.vo;

import org.jose4j.jwt.JwtClaims;
import org.lightningj.paywall.paymenthandler.Payment;
import org.lightningj.paywall.tokengenerator.JWTClaim;
import org.lightningj.paywall.util.Base58;
import org.lightningj.paywall.vo.amount.Amount;

import javax.json.JsonException;
import javax.json.JsonObject;
import javax.json.JsonObjectBuilder;
import java.time.Instant;

/**
 * Value object containing information needed to create
 * lightning invoice, generated by the PaymentHandler.
 *
 * Created by Philip Vendil on 2018-10-29.
 */
public class Order extends JWTClaim implements Payment {

    public static final String CLAIM_NAME = "payment";

    protected byte[] preImageHash;
    protected String description;
    protected Amount orderAmount;
    protected Instant expireDate;

    /**
     * Empty Constructor
     */
    public Order(){}

    /**
     * Default Constructor.
     *
     * @param preImageHash the generated preImageHash from PreImageData.
     * @param description description to display in the invoice. (Optional).
     * @param orderAmount the amount to create invoice for before eventual currency convertion. (Required)
     * @param expireDate the time when the payment should be considered expired and not accepted. (Required)
     */
    public Order(byte[] preImageHash, String description, Amount orderAmount, Instant expireDate) {
        this.preImageHash = preImageHash;
        this.description = description;
        this.orderAmount = orderAmount;
        this.expireDate = expireDate;
    }

    /**
     * JSON Parseable constructor
     *
     * @param jsonObject the json object to parse
     */
    public Order(JsonObject jsonObject) throws JsonException {
        super(jsonObject);
    }

    /**
     * Parse from JWTClaims constructor
     *
     * @param jwtClaims the JWT Tokens Claim set to extract data from.
     */
    public Order(JwtClaims jwtClaims) {
        super(jwtClaims);
    }

    /**
     *
     * @return the generated preImageHash from PreImageData.
     */
    public byte[] getPreImageHash() {
        return preImageHash;
    }

    /**
     *
     * @param preImageHash the generated preImageHash from PreImageData.
     */
    public void setPreImageHash(byte[] preImageHash) {
        this.preImageHash = preImageHash;
    }

    /**
     *
     * @return description to display in the invoice. (Optional).
     */
    public String getDescription() {
        return description;
    }

    /**
     *
     * @param description description to display in the invoice. (Optional).
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     *
     * @return the amount to create invoice for before eventual currency convertion. (Required)
     */
    public Amount getOrderAmount() {
        return orderAmount;
    }

    /**
     *
     * @param orderAmount the amount to create invoice for before eventual currency convertion. (Required)
     */
    public void setOrderAmount(Amount orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     *
     * @return the time when the payment should be considered expired and not accepted. (Required)
     */
    public Instant getExpireDate() {
        return expireDate;
    }

    /**
     *
     * @param expireDate the time when the payment should be considered expired and not accepted. (Required)
     */
    public void setExpireDate(Instant expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * Method that should set the objects property to Json representation.
     *
     * @param jsonObjectBuilder the json object build to use to set key/values in json
     * @throws JsonException if problems occurred converting object to JSON.
     */
    @Override
    public void convertToJson(JsonObjectBuilder jsonObjectBuilder) throws JsonException {
        addB58(jsonObjectBuilder,"preImageHash", Base58.encodeToString(preImageHash));
        addNotRequired(jsonObjectBuilder,"description",description);
        add(jsonObjectBuilder,"orderAmount", orderAmount);
        add(jsonObjectBuilder,"expireDate",expireDate);
    }

    /**
     * Method to read all properties from a JsonObject into this value object.
     *
     * @param jsonObject the json object to read key and values from and set object properties.
     * @throws JsonException if problems occurred converting object from JSON.
     */
    @Override
    public void parseJson(JsonObject jsonObject) throws JsonException {
        preImageHash = getByteArrayFromB58(jsonObject,"preImageHash", true);
        description = getStringIfSet(jsonObject,"description");
        orderAmount = Amount.parseAmountObject(getJsonObject(jsonObject,"orderAmount",true));
        expireDate = Instant.ofEpochMilli(getLong(jsonObject,"expireDate", true));
    }

    @Override
    public String getClaimName() {
        return CLAIM_NAME;
    }
}
