/*
 * ***********************************************************************
 *                                                                       *
 *  LightningJ                                                           *
 *                                                                       *
 *  This software is free software; you can redistribute it and/or       *
 *  modify it under the terms of the GNU Lesser General Public License   *
 *  (LGPL-3.0-or-later)                                                  *
 *  License as published by the Free Software Foundation; either         *
 *  version 3 of the License, or any later version.                      *
 *                                                                       *
 *  See terms of license at gnu.org.                                     *
 *                                                                       *
 *************************************************************************/
package org.lightningj.paywall.springboot2.paymenthandler;

import org.lightningj.paywall.paymenthandler.data.MinimalPaymentData;
import org.lightningj.paywall.util.Base64Utils;
import org.lightningj.paywall.vo.amount.Amount;
import org.lightningj.paywall.vo.amount.BTC;
import org.lightningj.paywall.vo.amount.CryptoAmount;

import javax.persistence.*;

/**
 * Demo payment data implementing the MinimalPaymentData requirements
 * for payment flow to work.
 * It is a simple JPA Entity with following columns:
 * <p><ul>
 * <li>id: primary id in database</li>
 * <li>preImageHash: unique preImageHash generated with the order.</li>
 * <li>orderAmount: the orderAmount in satoshis for this payment</li>
 * <li>settled: indicates if this order have been settled.</li>
 * </ul><p>
 */
@Entity
public class DemoPaymentData implements MinimalPaymentData {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    private Integer id;

    @Column(nullable = false)
    private String preImageHash;

    private long orderAmount;

    private boolean settled = false;

    /**
     *
     * @return Unique Id of database row.
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id Unique Id of database row.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Unique identifier of a payment in the system and also used in LightningHandler
     * to identify an invoice. Should be generated by TokenGenerator when
     * creating an order and not set manually.
     *
     * @return the unique identifier of a payment.
     */
    @Override
    public byte[] getPreImageHash() {
        return Base64Utils.decodeBase64String(this.preImageHash);
    }

    /**
     * @param preImageHash unique identifier of a payment in the system and also used in LightningHandler
     *                     to identify an invoice. Should be generated by TokenGenerator when
     *                     creating an order and not set manually.
     */
    @Override
    public void setPreImageHash(byte[] preImageHash) {
        this.preImageHash = Base64Utils.encodeBase64String(preImageHash);
    }

    /**
     * @return the requested amount for payment. This can be either a FiatAmount or CryptoAmount but
     * always make sure the systems configured CurrencyConverter supports this currency when converting
     * into a currency accepted by the LightningHandler later in the payment flow.
     */
    @Override
    public Amount getOrderAmount() {
        return new BTC(orderAmount);
    }

    /**
     * @param orderAmount the requested amount for payment. This can be either a FiatAmount or CryptoAmount but
     *                    always make sure the systems configured CurrencyConverter supports this currency when converting
     *                    into a currency accepted by the LightningHandler later in the payment flow.
     */
    @Override
    public void setOrderAmount(Amount orderAmount) {
        assert orderAmount instanceof CryptoAmount;
        this.orderAmount = ((CryptoAmount) orderAmount).getValue();
    }

    /**
     * @return true if related invoice have been settled in full.
     */
    @Override
    public boolean isSettled() {
        return this.settled;
    }

    /**
     * @param settled true if related invoice have been settled in full.
     */
    @Override
    public void setSettled(boolean settled) {
        this.settled = settled;
    }

    @Override
    public String toString() {
        return "DemoPaymentData{" +
                "id=" + id +
                ", preImageHash='" + preImageHash + '\'' +
                ", orderAmount=" + orderAmount +
                ", settled=" + settled +
                '}';
    }
}
