== Introduction

LightningJ Paywall is a project aimed at providing a simple to use framework to implement micro-payment functionality to
Java oriented Web Services using the Lightning Network. It is built to support Spring Framework and Spring Boot.

More information and source code can be found on the link:https://github.com/lightningj-org/paywall[Github site].
There it is possible to report issues and contribute code.

If you want updates on this project, follow https://twitter.com/LightningJ_org on twitter.

_Important_: This API is still in beta and API methods might change before real production release. +
*All use of this library is on your own risk.*

=== Overview

The LightningJ Paywall Framework has a goal to provide micro payment functionality to web services in Java.

* It contains a Java library with core functionality and a Spring Framework library for use in Spring and Spring Boot
applications.
* REST Services can be annotated with a @PaymentRequired annotation, triggering the need for a payment flow.
* The library uses a LND Lightning Node in the backend to manage invoices.
* It provides a JavaScript library  extending the standard XMLHttpRequest class with paywall functionality,
automatically regenerating a request after settlement.
* To minimize the latency times after settling an invoice is a WebSocket interface provided to push out
settlement data to the browser so it can regenerate the request as soon as possible.

The framework aims to simply cloud deployment by being as stateless as possible (on server side) by utilizing state in
encrypted and signed (JWT, Java Web Tokens) authentication tokens. This removes the need for stateful load balancers and
complex logic in a clustered environment.

In the initial step is all functionality contained in the same application, i.e connection
to Lightning Node and end-point for checking state, but in the future will more distributed configuration be available
in order to make the paywalled service to be as minimal as possible.

See <<gettingstarted, Getting Started section>> for a quick run through of the project.

=== License

This library is Open Source and released under the LGPL v3 License. A link
to the license agreement can be found link:LICENSE.txt[here].

=== Whats New

 * 0.1.0-beta, Inital release.

=== Roadmap

The framework will improve overtime with features requested, some ideas of future
features are:

* Support HODL Invoices.
* Javascript API should be packaged and uploaded to central repository.
* Support a distributed payment flow other that local where lightning node connection
  can be managed from a central system.
* Improved PaymentEventBus, possibility to subscribe to payment related events.

=== Release Distribution

All releases of the LightningJ Paywall framework are uploaded to maven central to be used
with Maven or Gradle under the group _org.lightningj.paywall_.

==== Release Signature Key

All releases are signed with the following link:lightningj-release-pubkey.asc[GPG Key].

GPG Key Fingerprint:

    7C0F 80B8 BD9F E3B8 1388  4BA1 9515 B31D DD9B BCCD